version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function modified vol-2.0"
    - zip -r deployment_package.zip lambda_function.py
  post_build:
    commands:
    - echo "Deploying to the Lambda from git"
    - aws lambda update-function-code --function-name  new_git --zip-file fileb://deployment_package.zip
artifacts:
  type: zip
  paths:
    - '*'
